<?xml version="1.0" encoding="UTF-8"?>
<!--
 Copyright (c) 2019, 2026 Obeo.
 This program and the accompanying materials
 are made available under the terms of the Eclipse Public License v2.0
 which accompanies this distribution, and is available at
 https://www.eclipse.org/legal/epl-2.0/

 SPDX-License-Identifier: EPL-2.0
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>fr.obeo.playground</groupId>
        <artifactId>sirius-components-restful-parent</artifactId>
        <version>1.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>sirius-components-restful-app</artifactId>

    <dependencies>
        <dependency>
            <groupId>fr.obeo.playground</groupId>
            <artifactId>sirius-components-restful</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.sirius</groupId>
            <artifactId>sirius-web-starter</artifactId>
            <version>${sirius.web.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.sirius</groupId>
            <artifactId>sirius-web-frontend</artifactId>
            <version>${sirius.web.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.sirius</groupId>
            <artifactId>sirius-components-flow-starter</artifactId>
            <version>${sirius.web.version}</version>
        </dependency>
        <dependency>
            <groupId>BPMN2</groupId>
            <artifactId>org.obeonetwork.dsl.bpmn2</artifactId>
            <version>${bpmn.version}</version>
        </dependency>
        <dependency>
            <groupId>BPMN2</groupId>
            <artifactId>org.obeonetwork.dsl.bpmn2.edit</artifactId>
            <version>${bpmn.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.uml2.plugins</groupId>
            <artifactId>org.eclipse.uml2.uml</artifactId>
            <version>${uml2.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.uml2.plugins</groupId>
            <artifactId>org.eclipse.uml2.common</artifactId>
            <version>2.5.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.uml2.plugins</groupId>
            <artifactId>org.eclipse.uml2.types</artifactId>
            <version>2.5.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.uml2.plugins</groupId>
            <artifactId>org.eclipse.uml2.uml.edit</artifactId>
            <version>5.5.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.uml2.plugins</groupId>
            <artifactId>org.eclipse.uml2.common.edit</artifactId>
            <version>2.5.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.uml2.plugins</groupId>
            <artifactId>org.eclipse.uml2.uml.resources</artifactId>
            <version>5.5.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.uml2.plugins</groupId>
            <artifactId>org.eclipse.uml2.uml.profile.standard</artifactId>
            <version>1.5.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>testcontainers-postgresql</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>testcontainers-junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.sirius</groupId>
            <artifactId>sirius-web-tests</artifactId>
            <version>${sirius.web.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.sirius</groupId>
            <artifactId>sirius-web-tests-data</artifactId>
            <version>${sirius.web.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
