
_UI_VariableConstraint_diagnostic_noname = Variable {1} has no name.
_UI_VariableConstraint_diagnostic_nameinvalid = Variable {1} has a name with spaces.
_UI_validateUniformDistribution_minMaxAreConsistentConstraint_diagnostic = the max property should be higher than the min property.
_UI_validateFormulaSetting_unknownVariable = Variable named "{2}" is unknown 
_UI_validateFormulaSetting_invalidSyntax = Invalid syntax : "{2}"