#

pluginName = fr.obeo.dsl.guesstimate Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Operation_type = Operation
_UI_Distribution_type = Distribution
_UI_Sheet_type = Sheet
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Operation_d_feature = D
_UI_Operation_c_feature = C
_UI_Operation_b_feature = B
_UI_Operation_e_feature = E
_UI_Operation_f_feature = F
_UI_Operation_a_feature = A
_UI_Operation_g_feature = G
_UI_Operation_out_feature = Out
_UI_Operation_name_feature = Name
_UI_Distribution_name_feature = Name
_UI_Distribution_definition_feature = Definition
_UI_Sheet_distributions_feature = Distributions
_UI_Sheet_operations_feature = Operations
_UI_Unknown_feature = Unspecified

_UI_Operation_variables_feature = Variables
_UI_Operation_formula_feature = Formula
_UI_Binomial_type = Binomial
_UI_Binomial_trials_feature = Trials
_UI_Binomial_p_feature = P
_UI_Sheet_sampleSize_feature = Sample Size
_UI_Normal_type = Normal
_UI_Triangular_type = Triangular
_UI_Uniform_type = Uniform
_UI_Binomial_probability_feature = Probability
_UI_Normal_mean_feature = Mean
_UI_Normal_standardDeviation_feature = Standard Deviation
_UI_Triangular_average_feature = Average
_UI_Triangular_max_feature = Max
_UI_Triangular_min_feature = Min
_UI_Uniform_lower_feature = Lower
_UI_Uniform_upper_feature = Upper
_UI_Poisson_type = Poisson
_UI_Poisson_probability_feature = Probability
_UI_Poisson_epsilon_feature = Epsilon
_UI_Triangular_mode_feature = Mode
_UI_Triangular_upper_feature = Upper
_UI_Triangular_lower_feature = Lower
_UI_Poisson_maxOccurrences_feature = Max Occurrences
_UI_Distribution_type_feature = Type
_UI_IntervalType_normal_literal = normal
_UI_IntervalType_uniform_literal = uniform
_UI_IntervalType_lognormal_literal = lognormal
_UI_Distribution_upper_feature = Upper
_UI_Distribution_lower_feature = Lower
_UI_IntervalType_proportion_literal = proportion
_UI_IntervalType_computed_literal = computed
_UI_Variable_type = Variable
_UI_Operation_inputs_feature = Inputs
_UI_Operation_output_feature = Output
_UI_Variable_name_feature = Name
_UI_Variable_definition_feature = Definition
_UI_Variable_type_feature = Type
_UI_Variable_upper_feature = Upper
_UI_Variable_lower_feature = Lower
_UI_Sheet_variables_feature = Variables
_UI_DistributionSetting_type = Distribution Setting
_UI_NormalDistribution_type = Normal Distribution
_UI_LogNormalDistribution_type = Log Normal Distribution
_UI_UniformDistribution_type = Uniform Distribution
_UI_BetaDistribution_type = Beta Distribution
_UI_TriangularDistribution_type = Triangular Distribution
_UI_BinomialDistribution_type = Binomial Distribution
_UI_PoissonDistribution_type = Poisson Distribution
_UI_ExponentialDistribution_type = Exponential Distribution
_UI_GammaDistribution_type = Gamma Distribution
_UI_NormalDistribution_mean_feature = Mean
_UI_NormalDistribution_sd_feature = Sd
_UI_LogNormalDistribution_scale_feature = Scale
_UI_LogNormalDistribution_shape_feature = Shape
_UI_UniformDistribution_min_feature = Min
_UI_UniformDistribution_max_feature = Max
_UI_BetaDistribution_alpha_feature = Alpha
_UI_BetaDistribution_beta_feature = Beta
_UI_TriangularDistribution_min_feature = Min
_UI_TriangularDistribution_max_feature = Max
_UI_TriangularDistribution_mode_feature = Mode
_UI_BinomialDistribution_trials_feature = Trials
_UI_BinomialDistribution_p_feature = P
_UI_PoissonDistribution_p_feature = P
_UI_PoissonDistribution_epsilon_feature = Epsilon
_UI_ExponentialDistribution_mean_feature = Mean
_UI_GammaDistribution_shape_feature = Shape
_UI_GammaDistribution_scale_feature = Scale
_UI_IntervalType_beta_literal = beta
_UI_IntervalType_triangular_literal = triangular
_UI_IntervalType_binomial_literal = binomial
_UI_IntervalType_poisson_literal = poisson
_UI_IntervalType_exponential_literal = exponential
_UI_IntervalType_gamma_literal = gamma
_UI_Variable_distribution_feature = Distribution
_UI_Variable_description_feature = Description
_UI_FormulaSetting_type = Formula Setting
_UI_FormulaSetting_formula_feature = Formula
_UI_FormulaSetting_inputs_feature = Inputs
_UI_IntervalType_formula_literal = formula
