#

bin.includes = .,\
               model/,\
               META-INF/,\
               plugin.xml,\
               plugin.properties
jars.compile.order = .
source.. = src-gen/,\
           src/,\
           src/main/resources/,\
           target/generated-sources/annotations/
