################################################################################################
# Copyright (c) 2019, 2026 Obeo.
# This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
################################################################################################
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.liquibase.change-log=classpath:db/db.changelog-master.xml
spring.data.elasticsearch.repositories.enabled=false
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

spring.servlet.multipart.max-file-size=256MB
spring.servlet.multipart.max-request-size=256MB

sirius.web.restfulemf.max-request-size=256MB
sirius.web.restfulemf.max-uncompressed-size=256MB
sirius.web.restfulemf.max-concurrent-transfers=2

sirius.web.enabled=*
sirius.components.cors.allowedOriginPatterns=*
