<?xml version="1.0" encoding="UTF-8"?>
<!--
 Copyright (c) 2026 Obeo.
 This program and the accompanying materials
 are made available under the terms of the Eclipse Public License v2.0
 which accompanies this distribution, and is available at
 https://www.eclipse.org/legal/epl-2.0/

 SPDX-License-Identifier: EPL-2.0
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>fr.obeo.dsl.guesstimate</groupId>
		<artifactId>fr.obeo.dsl.guesstimate.releng</artifactId>
		<version>0.0.7-SNAPSHOT</version>
		<relativePath>../fr.obeo.dsl.guesstimate.releng/pom.xml</relativePath>
	</parent>
	<artifactId>fr.obeo.dsl.guesstimate.configuration</artifactId>

	<dependencies>
		<dependency>
			<groupId>fr.obeo.dsl.guesstimate</groupId>
			<artifactId>fr.obeo.dsl.guesstimate</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>fr.obeo.dsl.guesstimate</groupId>
			<artifactId>fr.obeo.dsl.guesstimate.edit</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>fr.obeo.dsl.guesstimate</groupId>
			<artifactId>fr.obeo.dsl.guesstimate.views</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.common</artifactId>
			<version>2.45.0</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.ecore</artifactId>
			<version>2.42.0</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.edit</artifactId>
			<version>2.23.0</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.sirius</groupId>
			<artifactId>sirius-components-core</artifactId>
			<version>${sirius.web.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.sirius</groupId>
			<artifactId>sirius-components-emf</artifactId>
			<version>${sirius.web.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.sirius</groupId>
			<artifactId>org.eclipse.sirius.emfjson</artifactId>
			<version>2.5.4-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.sirius</groupId>
			<artifactId>sirius-components-collaborative-forms</artifactId>
			<version>${sirius.web.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.sirius</groupId>
			<artifactId>sirius-components-interpreter</artifactId>
			<version>${sirius.web.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.sirius</groupId>
			<artifactId>sirius-components-representations</artifactId>
			<version>${sirius.web.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.sirius</groupId>
			<artifactId>sirius-components-forms</artifactId>
			<version>${sirius.web.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.sirius</groupId>
			<artifactId>sirius-components-view</artifactId>
			<version>${sirius.web.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.sirius</groupId>
			<artifactId>sirius-components-view-form</artifactId>
			<version>${sirius.web.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.sirius</groupId>
			<artifactId>sirius-components-view-emf</artifactId>
			<version>${sirius.web.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.sirius</groupId>
			<artifactId>sirius-web-application</artifactId>
			<version>${sirius.web.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-beans</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</dependency>
		<dependency>
			<groupId>jakarta.annotation</groupId>
			<artifactId>jakarta.annotation-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
